version: 2

project_name: piggy-planner

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build
    main: ./
    binary: piggy-planner
    ldflags:
      - -s -w -X github.com/bernardoamorim7/piggy-planner.Version={{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

release:
  draft: true

archives:
  - id: archive
    builds: [build]
    format: zip
    # files:
    #   - LICENSE.md
    #   - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
