version: '3.8'

services:
  mariadb:
    image: mariadb:lts
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_volume:/var/lib/mariadb

volumes:
  piggy_planner_volume: